apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-demo-helm-content
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>prod</title>
    </head>
    <body>

    <h1>uat</h1>

    </body>
    </html>