apiVersion: v1
kind: Service
metadata:
  name: kargo-demo-helm
spec:
  type: NodePort
  selector:
    app: kargo-demo-helm
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
      nodePort: 32082